### ISSUE TITLE
adding folder to workspace breaks nested input

### ISSUE THREAD

**Issue by jankovicgd** [augustocdias/vscode-shell-command#43] opened 2022-07-08 09:02 UTC
I tried it with the Dependent Input Variables Usage example from the readme and with my own usecase. Seems that adding new folder to workspace breaks the addon, ie. it doesn't have the same behavior. Not sure if limitation or a fix is possible

**Comment by augustocdias** [comment] 2022-07-08 11:02
Can you post your config file please?

**Comment by jankovicgd** [comment] 2022-07-11 10:24
Sorry for the late reply, its the same from the example.

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Nested input",
            "command": "ls ${input:rootDir}/${input:childDir}",
            "type": "shell",
            "problemMatcher": []
        }
    ],
    "inputs": [
        {
            "id": "rootDir",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "command": "ls -1a"
            }
        },
        {
            "id": "childDir",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "command": "ls -1a ${input:rootDir}"
            }
        }
    ]
}
```

**Comment by augustocdias** [comment] 2022-07-11 12:08
I found an issue here:

https://github.com/augustocdias/vscode-shell-command/blob/e43fee7d399881b877cfb4105e5079b16fa8989e/src/lib/CommandHandler.ts#L127-L128

Not sure if we can do anything. We have to research on the vscode API. It is returning nothing so the variable is replaced with an empty string.

**Comment by jankovicgd** [comment] 2022-07-11 13:03
Thanks for looking in to it. The plugin is great otherwise, really useful to automatize some tasks.

**Comment by augustocdias** [comment] 2022-07-19 10:46
Can you check if the issue is fixed in the latest version?
I think #41 did the trick.

**Closed** 2022-07-26 08:12 UTC
Labels: bug
