### ISSUE TITLE
"command" should also support string arrays, just like the task command argument

### ISSUE THREAD

**Issue by CodingMarkus** [augustocdias/vscode-shell-command#70] opened 2023-11-20 10:24 UTC
Commands in VSCode can usually be either a string or an array. E.g. if you specify a task, you can do:

```
"command": [
    "commandA ....",
    "| commandB ...",
    "| commandC ...."
]
```

instead of 

```
"command": "commandA .... | commandB ... | commandC ...."
```

as breaking huge commands into chunks makes them way more readable. The implementation simply joins the array elements into a single string first.

Would be nice if this extension would also follow that pattern, as it makes it easier to write complex commands and it's also nice to have consistent behavior throughout build-in functons and extensions.

**Comment by MarcelRobitaille** [comment] 2024-01-22 17:02
@CodingMarkus I implemented this in [my fork](https://marketplace.visualstudio.com/items?itemName=marcelrobitaille.tasks-shell-input-ngx)

**Comment by MarcelRobitaille** [comment] 2024-01-22 17:15
This is a duplicate of #38

**Closed** 2024-01-24 17:20 UTC
Labels: enhancement, help wanted
